name: JavaScript Build

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
  push:
    branches:
      - "main"
    paths:
      - "Source/JavaScript/**"
  pull_request:
    branches:
      - "**"
    paths:
      - "Source/JavaScript/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node v16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: "https://registry.npmjs.org"

      - name: Yarn install
        run: yarn


      - name: Build JS/TS
        run: |
          export NODE_OPTIONS="--max-old-space-size=4096"
          yarn ci
